services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard
    container_name: balance-service-aspire-dashboard
    ports:
      - "18888:18888"
      - "4317:18889"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

  postgres:
    image: postgres:15.4-bullseye
    container_name: balance-service-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=balance_service
    logging:
      options:
        max-size: 10m
        max-file: 3
    ports:
      - 35433:5432
    volumes:
      - ./src/Infrastructure/Scripts/Migration.sql:/docker-entrypoint-initdb.d/init.sql

  localstack:
    image: localstack/localstack:3.0.2
    container_name: balance-service-localstack
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
      - SERVICES=sns
      - DISABLE_EVENTS=1
      - HOSTNAME=localstack-balance-service
      - LOCALSTACK_HOST=localstack-balance-service
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  setup-localstack:
    image: amazon/aws-cli
    container_name: balance-service-setup-localstack
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-west-1
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 5
      
        aws --endpoint-url=http://localstack:4566 sns create-topic --name account-updated-topic.fifo --attributes FifoTopic=true,ContentBasedDeduplication=false --region eu-west-1
        aws --endpoint-url=http://localstack:4566 sns create-topic --name transaction-updated-topic.fifo --attributes FifoTopic=true,ContentBasedDeduplication=false --region eu-west-1
        aws --endpoint-url=http://localstack:4566 sns create-topic --name hold-updated-topic.fifo --attributes FifoTopic=true,ContentBasedDeduplication=false--region eu-west-1
      "
    volumes:
      - ./dev_env:/project/dev_env
    depends_on:
      - localstack