apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-service-api
  namespace: balance-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: balance-service-api
  template:
    metadata:
      labels:
        app: balance-service-api
    spec:
      containers:
        - name: balance-service-api
          image: balance-service-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          envFrom:
            - secretRef:
                name: balance-service-secrets
            - configMapRef:
                name: balance-service-config
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
