apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: abor-api-hpa
  namespace: abor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: abor-api
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
